# Introduction to Statistics

Statistics is the science of collecting,
organizing, analyzing and interpreting data.

In [1]:
print("Hello Statistics")

Hello Statistics

# Introduction to Statistics and Data Analysis

## Data Science & Machine Learning Foundation

### Objective

This notebook covers:

- What is Statistics
- Types of Data
- Numerical and Categorical Data
- Population and Sample
- Variables
- Features and Target Variables

Author:
Sonali Salvi

In [2]:
# Import required libraries

import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

## Creating Student Performance Dataset

We create a small dataset containing:

- Student Name
- Age
- Marks
- City

This dataset will help us understand different types of data.

In [4]:
students = pd.DataFrame({
    "Name": [
        "John",
        "Erik",
        "Sara",
        "Oskar",
        "Jane"
     ],

     "Age": [
        20,
        21,
        19,
        22,
        23
    ],

    "Marks": [
        85,
        90,
        60,
        95,
        70
    ],

    "City": [
        "Mumbai",
        "Delhi",
        "Pune",
        "Mumbai",
        "Delhi"
    ]
})

print(students)

students

    Name  Age  Marks    City
0   John   20     85  Mumbai
1   Erik   21     90   Delhi
2   Sara   19     60    Pune
3  Oskar   22     95  Mumbai
4   Jane   23     70   Delhi

    Name  Age  Marks    City
0   John   20     85  Mumbai
1   Erik   21     90   Delhi
2   Sara   19     60    Pune
3  Oskar   22     95  Mumbai
4   Jane   23     70   Delhi

## Understanding Dataset Shape

Rows represent observations.

Columns represent variables/features.

In [5]:
students.shape # 5 students, 4 variables

(5, 4)

In [6]:
students.columns

Index(['Name', 'Age', 'Marks', 'City'], dtype='object')

In [7]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
 3   City    5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

##Find Numerical Columns

In [11]:
numerical_columns = students.select_dtypes(
    include = np.number
)

numerical_columns

   Age  Marks
0   20     85
1   21     90
2   19     60
3   22     95
4   23     70

##Find Categorical Columns

In [10]:
categorical_columns = students.select_dtypes(
    include = "object"
)

categorical_columns

    Name    City
0   John  Mumbai
1   Erik   Delhi
2   Sara    Pune
3  Oskar  Mumbai
4   Jane   Delhi

In [12]:
students

# Q1. How many observations are present? - 5 observations
# Q2. How many features/columns? - 4 Features
# Q3. Which columns are numerical? - Age, Marks
# Q4. Which columns are categorical? - City
# Q5. If we want to predict Marks:
# What are:
# Features (X)? : Name,Age,City
# Target (Y)? : Marks

    Name  Age  Marks    City
0   John   20     85  Mumbai
1   Erik   21     90   Delhi
2   Sara   19     60    Pune
3  Oskar   22     95  Mumbai
4   Jane   23     70   Delhi